version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # 👈 public port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # 👈 mount your config
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
